name = "Namez Arthur"
description = "Tokyo Bartendar."
keywords = "Arthur Kreiter, actor, filmography, bartendar"
image = ""
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-XLJ81DCZFV"
base_url = "https://thevahidal.github.io/jake"

[[sections]]
title = "My Latest Video"
direction = "column"
item_style = "outline"
[[sections.items]]
embed_url = "https://www.youtube.com/embed/x0gUY9ddjQY"

[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://www.instagram.com/arthurkkreiter?igsh=MWFpMmI5cTl3ZTBpbQ%3D%3D&utm_source=qr"
[[sections.items]]
icon = "https://cdn.simpleicons.org/tiktok"
title = "Tik Tok"
url = "http://www.tiktok.com/@namezarthur"
[[sections.items]]
icon = "https://cdn.simpleicons.org/youtube"
title = "Youtube"
url = "https://youtube.com/@arthurvlogsnow?si=y0tNsEunUd9d77BD"
[[sections.items]]
title = "Linked in"
icon = "https://cdn.simpleicons.org/rottentomatoes/ffffff"
url = "www.linkedin.com/in/arthur-kreiter-5ab7242ab"
